certificate_provider: letsencrypt
buildbot_server_name: buildbot.covid-videoplattform.de

buildbot_builders:
  infrastructure:
    repos:
      - name: github covid-videoplattform
        workdir: covid-videoplattform
        repourl: https://github.com/covid-videoplattform/covid-videoplattform.git
    shell_commands:
      - name: terraform init
        command: terraform init
        workdir: covid-videoplattform
      - name: ansible
        command: ansible-playbook infrastructure.yaml -v
        workdir: covid-videoplattform
      - name: copy inventory
        command: cp inventory.json ..
        workdir: covid-videoplattform
  terminfrontend:
    repos:
      - name: github covid-videoplattform
        workdir: covid-videoplattform
        repourl: https://github.com/covid-videoplattform/covid-videoplattform.git
      - name: github ansible-role-terminfrontend
        workdir: ansible-roles/terminfrontend
        repourl: https://github.com/covid-videoplattform/ansible-role-terminfrontend.git
      - name: github django-webfrontend
        workdir: django-webfrontend
        repourl: https://github.com/covid-videoplattform/django-webfrontend.git
    shell_commands:
      - name: ansible
        command: ansible-playbook -i ../inventory.json playbook.yaml --limit terminfrontend -v
        workdir: covid-videoplattform
  jitsi:
    repos:
      - name: github covid-videoplattform
        workdir: covid-videoplattform
        repourl: https://github.com/covid-videoplattform/covid-videoplattform.git
      - name: github ansible-role-jicofo
        workdir: ansible-roles/jicofo
        repourl: https://github.com/covid-videoplattform/ansible-role-jicofo.git
      - name: github ansible-role-jitsi-meet-web
        workdir: ansible-roles/jitsi-meet-web
        repourl: https://github.com/covid-videoplattform/ansible-role-jitsi-meet-web.git
      - name: github ansible-role-jitsi-monitoring
        workdir: ansible-roles/jitsi-monitoring
        repourl: https://github.com/covid-videoplattform/ansible-role-jitsi-monitoring.git
      - name: github ansible-role-jitsi-monitoring-client
        workdir: ansible-roles/jitsi-monitoring-client
        repourl: https://github.com/covid-videoplattform/ansible-role-jitsi-monitoring-client.git
      - name: github ansible-role-jitsi-prosody
        workdir: ansible-roles/jitsi-prosody
        repourl: https://github.com/covid-videoplattform/ansible-role-jitsi-prosody.git
      - name: github ansible-role-jitsi-videobridge
        workdir: ansible-roles/jitsi-videobridge
        repourl: https://github.com/covid-videoplattform/ansible-role-jitsi-videobridge.git
      - name: github ansible-role-reverse-proxy
        workdir: ansible-roles/reverse-proxy
        repourl: https://github.com/covid-videoplattform/ansible-role-reverse-proxy.git
    shell_commands:
      - name: hello world
        command: echo Hello World!
        workdir: covid-videoplattform
