---

- hosts: bastion_servers
  roles:
    - name: nginx
    - name: ansible
    - name: terraform
    - name: buildbot
  tasks:
    - name: required debian packages
      apt:
        pkg:
          - etcd-server
    - name: automatically accept new ssh host keys
      lineinfile:
        line: StrictHostKeyChecking accept-new
        regex: '^[# ]*StrictHostKeyChecking'
        path: /etc/ssh/ssh_config
