---

- hosts: reverse_proxies
  roles:
    - role: nginx
    - role: certificate
      vars:
        certificate_name: "{{ jitsi_domain }}"
        certificate_directory: /etc/ssl
        certificate_key_usage:
          - digitalSignature
          - keyEncipherment
        certificate_extended_key_usage:
          - serverAuth
        certificate_common_name: "{{ jitsi_domain }}"
    - role: reverse-proxy

- hosts: jitsi_prosody_servers
  roles:
    - role: jitsi-prosody

- hosts: jicofo_servers
  roles:
    - role: jicofo

- hosts: jitsi_videobridges
  roles:
    - role: jitsi-videobridge

- hosts: jitsi_webservers
  roles:
    - role: jitsi-meet-web

- hosts: bastion_servers
  roles:
    - role: nginx
    - role: certificate
      vars:
        certificate_name: monitoring
        certificate_directory: /etc/ssl
        certificate_key_usage:
          - digitalSignature
          - keyEncipherment
        certificate_extended_key_usage:
          - serverAuth
        certificate_common_name: "{{ grafana_domain }}"
    - role: jitsi-monitoring

- hosts: all
  roles:
    - role: jitsi-monitoring-client
