---
- hosts:
  - videobridges
  roles:
    - role: ansible-role-jitsi-videobridge

- hosts:
  - web_servers
  roles:
    - role: ansible-role-jitsi-meet-web

- hosts:
  - jicofo
  roles:
    - role: ansible-role-jicofo

- hosts:
  - prosody_servers
  roles:
    - role: ansible-role-prosody
