---
- hosts:
  - videobridges
  roles:
    - role: jitsi-videobridge

- hosts:
  - web_frontends
  roles:
    - role: jitsi-meet-web

- hosts:
  - jicofo_servers
  roles:
    - role: jicofo

- hosts:
  - prosody_servers
  roles:
    - role: prosody
